# Generated by Django 3.1.7 on 2021-02-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Descrição sobre o produto', verbose_name='Descricao'),
        ),
    ]
